version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ${PWD}/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/www/index.php:/var/www/index.php
    networks:
      - internal
      - public
    expose:
      - "80"
    ports:
      - "80:80"

  php:
    build: .
    container_name: php
    restart: always
    volumes:
      - ${PWD}/php/php.ini:/etc/php/php.ini
      - ${PWD}/www/index.php:/var/www/index.php
    networks:
      - internal
    ports:
      - "9000"
    healthcheck:
      test: curl -f http://nginx | grep 'works' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  internal:
  public:
